name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.jpg
    - assets/cartoon_classroom.PNG
    - assets/cartoon_night_sky.jpg
    - assets/quadratic_formula.PNG
    - assets/surge_current.jpg
    - assets/cartoon_house.PNG
    - assets/emergency_kit.jpg
    - assets/elementaryGame.PNG
    - assets/powerOutage.PNG
    - assets/microwaveOff.PNG
    - assets/middleschoolGame.PNG
    - assets/tap_glass_sink.jpg
    - assets/open_fridge.PNG
    - assets/internetGraphic.png
    - assets/constructionWork.jpg
    - assets/stormUri.jpg
    - assets/fallenPole.PNG
    - assets/hurricane.PNG
    - assets/lineEquipment.PNG
    - assets/grackles.jpg
    - assets/squirrel.PNG
    - assets/AC_Unit.PNG
    - assets/LawOfCooling.PNG
    - assets/PowerTycoon.PNG
    - assets/powerOutage2.jpg
    - assets/outletImage.jpg
#  fonts:
#   - family: NameOfFont
#     fonts:
#      - asset: fonts/NameOfFont.ttf
